// app/api/products/[proid]/route.js
import { Product } from "@/lib/model/product";
import mongoose from 'mongoose';
import { connectionStr } from "../route";
import { NextResponse } from "next/server";

export async function PUT(req, content) {
    // console.log(content)
    const productId = content.params.proid; //proid filename
    // console.log(productId) // 66c30fa18776d268ec0ce69b generated by mongoDB

    const filter = {_id: productId} // as stored in mongoDB

    const payload = await req.json();
    // console.log(payload); // { name: 'Oppo XHR' } Postman>Body>raw>JSON

    await mongoose.connect(connectionStr);
    const result = await Product.findOneAndUpdate(filter, payload); // Product came from schema

    return NextResponse.json({result, success: true})
}

export async function GET(_, content) {

    const productId = content.params.proid;

    const record = {_id: productId}

    await mongoose.connect(connectionStr);
    const result = await Product.findById(record);

    return NextResponse.json({result, success: true})
}

export async function DELETE(_, content) {

    const productId = content.params.proid;

    const record = {_id: productId}

    await mongoose.connect(connectionStr);
    const result = await Product.deleteOne(record);

    return NextResponse.json({result, success: true})
}